networks:
  chatbot-network:
services:
  chatbot:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - chatbot-network
